In [ ]:
# Statistics
# Introduction to Numpy

In [2]:
import numpy as np
import pandas as pd

In [16]:
a1 = np.arange(11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
x1=[1,2,3,4,5]
x2=[6,7,8,9,10]
type(x1)

list

In [11]:
arr2d=np.array([x1,x2])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
a2=[2,4,6,3,36,7,2,5,4,6,8,3,3,6,8,4,23]

In [42]:
del a2[2]

In [43]:
a2

[2, 4, 3, 36, 7, 2, 5, 4, 6, 8, 3, 3, 6, 8, 4]

In [4]:
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])

In [ ]:
# Whenever there is 'and' in the scenario there is intersection.
# Whenever there is 'or' in the scenario there is union.

In [5]:
np.intersect1d(a1,a2)

array([3, 6, 8])

In [6]:
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.isin(a1,a2)

array([ True, False,  True, False,  True, False])

In [10]:
np.setdiff1d(a1,a2)

array([1, 7, 9])

In [11]:
np.setxor1d(a1,a2)

array([ 1,  2,  4,  5,  7,  9, 10])

In [16]:
mat1=np.array([[2,3,4],[1,0,5]])

In [17]:
mat2=np.array([[1,0],[2,5],[4,3]])

In [18]:
mat1

array([[2, 3, 4],
       [1, 0, 5]])

In [19]:
mat2

array([[1, 0],
       [2, 5],
       [4, 3]])

In [23]:
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])

In [24]:
np.dot(x1,x2)

np.int64(-4)

In [25]:
np.cross(x1,x2)

array([ -5, -14, -13])

In [26]:
x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])

In [28]:
from numpy import linalg

In [29]:
np.linalg.det(x3)

np.float64(-1.0)

In [30]:
from numpy import random

In [89]:
a1=np.random.rand(10,3)

In [98]:
np.random.rand(10,2)

array([[0.05564783, 0.57534972],
       [0.17651807, 0.50495907],
       [0.95569436, 0.38083717],
       [0.76709123, 0.56881923],
       [0.85661519, 0.2740256 ],
       [0.89489154, 0.38485573],
       [0.69234736, 0.2742413 ],
       [0.99418387, 0.5627047 ],
       [0.02607449, 0.01733886],
       [0.01596549, 0.48045751]])

np.random.randint(5,50)

In [76]:
np.random.randint(5,50,15)

array([35, 28, 14, 34, 37, 42, 28, 27, 23, 27, 16, 29,  9, 15, 37])

In [87]:
np.round(a1,2)

array([[0.31, 0.53],
       [0.4 , 0.39],
       [0.86, 0.77],
       [0.06, 0.12],
       [0.21, 0.03],
       [0.52, 0.21],
       [0.97, 0.56],
       [0.04, 0.13],
       [0.55, 0.19],
       [0.95, 0.59]])

In [99]:
a1 = np.array([4,5,5,8,5,3,6])

In [100]:
a1

array([4, 5, 5, 8, 5, 3, 6])

In [101]:
a1.iloc[2]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'