# **Numpy**

In [ ]:
import numpy as np
import pandas as pd

Data Structures

> # Data Structures (N dimension array)

In [ ]:
# type - what kind of data structure we will be working on
x1=[1,2,3,4]
type(x1)

a1=np.array(x1)
# converts list into array
type(a1)

numpy.ndarray

In [ ]:
x2=[6,7,9,1]

a2=np.array([x1,x2])
#2D array
a2

array([[1, 2, 3, 4],
       [6, 7, 9, 1]])

In [ ]:
# creating list
x1=list(range(11)) # The range function makes the array of values from 0 to n-1 (here n is 11 therefore 0 to (11-1) i.e. 10)
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a1=np.arange(11) # It is same as the range function used to create x1 as above
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1 = np.array([4,3,8,9,5])
a1

array([4, 3, 8, 9, 5])

In [ ]:
a1=np.array([4,3,8,9,5])
a1
np.append(a1,3) # just for display, will not save "Save"
a1=np.append(a1,3) # will show in list -- like "Save as"

a2=np.array([2,8,9])
a2

a3=np.concatenate((a1,a2))
a3 # concatenated- new array is stored as a3
x2=[5,3,6,7,3,8,9,3]
# remove, pop, del
x2.remove(3)
a2

x2.pop() # gives the values which has been removed, not the list

del x2[3]
x2

[5, 6, 7, 8, 9]

In [ ]:
# properties of array which list cant do
#select specific range


In [ ]:
a1=np.array([3,6,5,7,8])
a2=np.insert(a1,3,9)
a2
a2=np.insert(a1,1,4) # array,index,value
a2
np.delete(a2,2) # array,index

a2
# "==" True or false -- comparision



array([3, 4, 6, 5, 7, 8])

In [ ]:
a1=np.array([11,16,4,3,2,8,0,6])
len(a1)

a2=a1.reshape(4,2) # reshape- Converting 1D to 2D within given rows,col
a2

array([[11, 16],
       [ 4,  3],
       [ 2,  8],
       [ 0,  6]])

In [ ]:
a2=a1.reshape(2,2) # this wont work -- no of elements 8 so it cant either 4x2 or 2x4
a2=a1.reshape(5,2)


record kar

In [ ]:
# how many dimensions???- count no of sq. brackets

In [ ]:
a1=np.array([11,16,4,3,2,8,0,6])
a3=a1.reshape(-1,1)
a3 # -1= no of rows free, but ensure that no of columns is 1
a2=a1.reshape(-1,2) # no of rows free(python will decide), but 2 columns
a2
#array([[11, 16],
#       [ 4,  3],
#       [ 2,  8],
#       [ 0,  6]])

# print row 2
a2[1] # index starts with 0 , so 0 1
a2[1,:] #
a2[:,1] # 2nd column


a2[[2,3],:] #multiple rows  , will give rows with index 2 and 3

a2[:,[0,1]] # multiple columns , column with index 0 and 1


array([[11, 16],
       [ 4,  3],
       [ 2,  8],
       [ 0,  6]])

In [ ]:
newcol=np.array([3,1,7,9])
newcol=newcol.reshape(-1,1)
newcol # row of values converted in column values


array([[3],
       [1],
       [7],
       [9]])

In [ ]:
# hstack -- adding column , array will grow horizontally so hstack
# vstack -- adding row , array will grow vertically so vstack

In [ ]:
a3=np.hstack([a2,newcol]) # added new column  --- hstack([array,colname])
a3

newrow=np.array([2,3,4])
a3=np.vstack([a3,newrow]) # added new row --vstack([array,rowname])
a3

a3=np.insert(a3,3,[23,56,77],axis=0) # adding row at specific position, [arrayname,index to insert,values,axis=0 tells row]
a3

a3=np.insert(a3,2,[11,12,13,14,15,16],axis=1)
a3

# delete/ remove row index 1,3
a4=np.delete(a3,(1,3),axis=0)
a4
#delete / remove col index 1,3
a5=np.delete(a3,(1,3),axis=1)
a5

array([[11, 11],
       [ 4, 12],
       [ 2, 13],
       [23, 14],
       [ 0, 15],
       [ 2, 16]])

In [ ]:
# BROADCASTING- exceptionally makes array diff from list,
#               makes it possible to repeat same operation across all the values
#               which is not possible with list,
#               order of precedence will be the same

a1=np.array([4,7,6,8,9])
a2=np.array([4,2,7,6,3])

array([ 8,  9, 13, 14, 12])

In [ ]:
a1+5
a1+a2

array([ 8,  9, 13, 14, 12])

In [ ]:
a1=np.array([4,7,6,8,9])
a2=np.array([4,2,7])
a1+a2 # error - recycling of values does not happen in python, no of elements in both arrays must be equal


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
a1=np.array([3,5,7,6,8,9,2,4,6,8,9,12])
len(a1)
a2=a1.reshape(3,4)
a2

array([[ 3,  5,  7,  6],
       [ 8,  9,  2,  4],
       [ 6,  8,  9, 12]])

In [ ]:
a3=np.array([2,4,6,8])
a2+a3 #across all the rows

array([[ 5,  9, 13, 14],
       [10, 13,  8, 12],
       [ 8, 12, 15, 20]])

In [ ]:
#across rows we dont need reshape, across columns we need to jc ]reshape and then perform operations

In [ ]:
a3=np.array([3,4,5])

a4=a3.reshape(-1,1)

a2+a4

array([[ 6,  8, 10,  9],
       [12, 13,  6,  8],
       [11, 13, 14, 17]])

In [ ]:
a1[[2,3,4]] #gets the value at index 2,3 and 4 --array([7, 6, 8])
a1[1] #gets the value at index 1  -- np.int64(5)

np.int64(5)

In [ ]:
#takes input of condition that needs to be checked

# input to np.where command is a condition that needs to be checked
# output of np.where command are the indices where that condition is found to be true

# index=np.where(<condition>)

a1=np.array([14,17,9,6,11,1,3,15])

In [ ]:
# Values which are greater than 4
a2=np.where(a1>4)
a2
#gives output in tuple,inside tuple there is an array
#len(a2) --> 1, a2 is tuple ,has 1 array- counts this as 1 element so count is 1


(array([0, 1, 2, 3, 4, 7]),)

In [ ]:
# How many values are greater than 4

#len(a2[0]) --> length of array
len(a2[0])

(a1>4).sum()


np.int64(6)

In [ ]:
# what are the values that are greater than 4

a1[a2] # can give error
a1[a2[0]]  # safer

array([14, 17,  9,  6, 11, 15])

In [ ]:
x1 = (np.arange(48)).reshape(6,8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x2 = np.resize(x1,(12,4))
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [ ]:
x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays
x3

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [ ]:
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
x4 = np.split(x1,[2,4,5], axis=1)    # splitting happens vertically
x4

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27],
        [34, 35],
        [42, 43]]),
 array([[ 4],
        [12],
        [20],
        [28],
        [36],
        [44]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31],
        [37, 38, 39],
        [45, 46, 47]])]

In [ ]:
b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
b
c = sorted(b)
c      #sorts the array in increasing order
c = sorted(b)[::-1]    # sorts the array in the decreasing order
c
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 column
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

# axis=0  - top row will have least value
            #bottom row will have all highest values

# axis=1  - leftmost column will have least values
           #rightmost columns will have highest values

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged


array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [ ]:
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [ ]:
b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])

b=b.reshape(3,4)
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
ind=np.where(b>=4)
ind

#(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))
#.            row index                 column index
#. ex- [0,1],[0,3],[1,0],[1,1],[1,2],[1,3],[2,3] --- where values >=4


# how many values
len(ind[1])

#what are the values which are b>=4
b[ind]

array([4, 7, 6, 5, 9, 8, 5])

In [ ]:
type(ind)

tuple

In [ ]:
len(ind)

2

In [ ]:
# Repeating elements - as block -- 5 8 3 5 8 3

r1=[5,8,3]
r2=r1*3
r2

[5, 8, 3, 5, 8, 3, 5, 8, 3]

In [ ]:
# repeating elements individually  -- 5 5 5 8 8 8 3 3 3
a1=np.array([5,8,3])
a2=np.repeat(a1,3)
a2

# if u want each value to repeat different number of times -- 5 will repeat 2 times, 8 will repeat 5 times , 3 will repeat 3 times
a2.repeat(a1,[2,5,3])

array([5, 5, 5, 8, 8, 8, 3, 3, 3])

In [ ]:
np.sort(a1) # gives sorted values

array([3, 5, 8])

In [ ]:
np.argsort(a1) # will give index of sorted values

array([2, 0, 1])

In [ ]:
a1[np.argsort(a1)]  # will give the values

array([3, 5, 8])

In [ ]:
a2=np.array([6,4,8,3,2,5,7,9,0])
np.argsort(a2)
a2[np.argsort(a2)]

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1=np.array([6,0,5,4,8,7,6,2,2,5,7,1,8,1])
len(a1)

14

In [ ]:
a2=set(a1)
len(a2)
a2

#give only unique values
np.unique(a1)


np.unique(a1,return_counts=True)
# (array([0, 1, 2, 4, 5, 6, 7, 8]), array([1, 2, 2, 1, 2, 2, 2, 2]))
#  first array - unique values     2nd array-no of times each value is repeated



np.unique(a1,return_index=True)
# (array([0, 1, 2, 4, 5, 6, 7, 8]), array([ 1, 11,  7,  3,  2,  0,  5,  4]))
#.  first array - unique values.   2nd array - gives index where it occurs first



# gives the index where that values are present -- a1==2 -- 2 is present at 7th and 8th index
np.where(a1==2)

(array([7, 8]),)